services:
  frontend:
    build: ./frontend
    ports:
      - "5180:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always
    
